/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT!
 *
 * This file was generated by the `nest` script from 'flat.json'.
 * To update it, run: `npm run locale:nest <locale>`
 */


export interface LocaleSchema {
    settings: {
        toolbar: {
            reset: {
                notice: string;
                tooltip: string;
            };
            sidebar: {
                tooltip: string;
            };
        };
    };
}
