/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT!
 *
 * This file was generated by the `nest` script from 'flat.json'.
 * To update it, run: `npm run locale:nest <locale>`
 */
const Locale = {
    settings: {
        toolbar: {
            reset: {
                notice: "Settings have been reset to default.",
                tooltip: "Reset settings to default"
            },
            sidebar: {
                tooltip: "Toggle sidebar"
            }
        }
    }
};
export default Locale;
