/**
 * ⚠️ AUTO-GENERATED FILE — DO NOT EDIT!
 *
 * This file was generated by the `nest` script from 'flat.json'.
 * To update it, run: `npm run locale:nest <locale>`
 */
import type { LocaleSchema } from '../../types/interfaces';
declare const Locale: LocaleSchema;
export default Locale;
